name: Push to Hugging Face
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  hf-push:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      REPO : ${{ vars.REPO }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - run: |
          git push https://Anirban0011:$HF_TOKEN@huggingface.co/spaces/Anirban0011/$REPO master:main